//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace interf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avto
    {
        public string Государственный_номер { get; set; }
        public Nullable<int> Год_выпуска { get; set; }
        public string Тип { get; set; }
        public int Стоимость_аренды { get; set; }
        public Nullable<int> Стоимость_аренды_за_МКАДом { get; set; }
        public string Дополнительные_услуги { get; set; }
    }
}
